/**
 * JavaCC template file created by SF JavaCC plugin 1.5.28+ wizard for JavaCC 1.5.0+
 */
options
{
  static = false;
}

PARSER_BEGIN(DateParser)
package date;
public class DateParser {
}
PARSER_END(DateParser)

SKIP:
{
" "
}

TOKEN : 
{
  < DATE: < TWO_DIGIT >"-"< TWO_DIGIT>"-"< TWO_DIGIT ><TWO_DIGIT>>
| < TWO_DIGIT: (["0"-"9"]) {2} >
| < AMPM: "am"|"pm" >
| < TIME: <TWO_DIGIT>":"<TWO_DIGIT> >
}

void DateTime() : {}{<DATE><TIME>(<AMPM>)}